### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by Ygarr** [vadrian89/cumulus-qt#1] opened 2017-01-08 12:59 UTC
Freezes  when start not from administrator(root)
Freezes after settings - m/s

P.S. Where do I can find config file?

**Comment by vadrian89** [comment] 2017-01-08 13:04
Can you let me know, distribution name, version, DE and installation location? 

Config file should be: ~/.config/Visoft/Cumulus.conf

Thanks!

**Comment by vadrian89** [comment] 2017-01-08 13:05
Also are you using the online installer?

**Comment by Ygarr** [comment] 2017-01-08 13:10
Yes - online. 
After re-install
![2017-01-08-150650_592x511_scrot](https://cloud.githubusercontent.com/assets/14309871/21750128/8b60da3a-d5b4-11e6-81ed-9aba1e68422c.png)

**Comment by vadrian89** [comment] 2017-01-08 13:34
Sorry again for this, but I need to know those details I mentioned above.
Distribution name, version, desktop environment and installation location so I can try and pinpoint the issue

**Comment by Ygarr** [comment] 2017-01-08 14:28
Sorry was digressed
Distribution - Debian Sid.
Installation location: /home/myname/Cumulus
○ → inxi -b
System:    Host: sidbox Kernel: 4.9.1-towo.1-siduction-amd64 x86_64 (64 bit)
           Desktop: LXDE (Openbox 3.6.1)
           Distro: siduction 15.1.0 Paint It Black - lxde - (201601171107)
Machine:   Device: desktop System: navigator product: X500H
           Mobo: navigator model: X500H
           BIOS: American Megatrends v: 4.6.5 date: 09/30/2013
Battery    BAT0: charge: 57.5 Wh 98.2% condition: 58.6/79.0 Wh (74%)
CPU:       Dual core Intel Core i5-4200U (-HT-MCP-) speed/max: 899/2600 MHz
Graphics:  Card: Intel Haswell-ULT Integrated Graphics Controller
           Display Server: X.Org 1.19.0 drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile
           GLX Version: 3.0 Mesa 12.0.3
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169
           Card-2: Intel Wireless 7260 driver: iwlwifi
Drives:    HDD Total Size: 500.1GB (15.1% used)
Info:      Processes: 201 Uptime: 1:51 Memory: 1460.3/7910.9MB
           Client: Shell (bash) inxi: 2.3.5

**Comment by vadrian89** [comment] 2017-01-10 08:18
Hy Ygarr, 

Sorry for the late response, I have tried reproducing this issue on live-cd image for debian lxde version but to no avail. The application starts normally in both Virtualbox and normal boot. 
Can I ask your assistance with further with this issue?  
Download the installer again, install and start the application from terminal and make a screenshot with the terminal & application and attach it here.

**Comment by Ygarr** [comment] 2017-01-12 00:08
1. I have reinstalled software. No troubles (like download error) were met. All is OK.
2. After run I saw this:
![2017-01-12-020333_1760x603_scrot](https://cloud.githubusercontent.com/assets/14309871/21871610/e9752dc4-d86b-11e6-96df-e00b80f7397f.png)
That is frozen app.

**Comment by Ygarr** [comment] 2017-01-12 00:10
3. Than I removed config file. And app runs normally.
4. The content of config file before and after removing you can see on screenshot:
![2017-01-12-020514_1716x1010_scrot](https://cloud.githubusercontent.com/assets/14309871/21871649/3906fe3a-d86c-11e6-934e-b1f359fa3f93.png)

**Comment by Ygarr** [comment] 2017-01-12 00:18
5. Then I set colour, city and m/s - all seems fine .
6. Then I closed app and started again:
![2017-01-12-021802_755x630_scrot](https://cloud.githubusercontent.com/assets/14309871/21871820/5d6b4e4c-d86d-11e6-9679-2db62ff910c8.png)

**Comment by vadrian89** [comment] 2017-01-12 07:09
I think the issue is the web engine.....I will upgrade the app in the incoming days from Qt5.5.1 to Qt5.6.2 and see how it goes. 
Thanks for taking your time to help.

**Comment by vadrian89** [comment] 2017-01-12 17:42
I have updated the application with Qt5.6.2 version.
If you still have the application installed can you run the maintenancetool from inside the installation folder and run update on the application?

**Comment by Ygarr** [comment] 2017-01-13 20:40
1. Before updating I removed config file and started application.
2. The application worked fine. As far as I remember, I even rebooted the computer and after it app works.

**Comment by Ygarr** [comment] 2017-01-13 20:44
3. I saw your message and ran update with "maintenancetool" and launched Cumulus again immediately. But:
![2017-01-13-224410_415x588_scrot](https://cloud.githubusercontent.com/assets/14309871/21945042/d500fa90-d9e1-11e6-8012-4969477b6562.png)

**Comment by Ygarr** [comment] 2017-01-13 20:44
4. I gonna remove config again and restart app

**Comment by Ygarr** [comment] 2017-01-13 21:10
5. After rebooting and removing config problem still exists but location of window is top-left.
6. I did some system routines. than made restore-minimize actions. And after "Raise" window action app began works normally.
7. Now it seems works normally but cannot update:
![2017-01-13-230954_375x600_scrot](https://cloud.githubusercontent.com/assets/14309871/21945705/6c9ecea6-d9e5-11e6-867c-527bf333d0c1.png)

**Comment by Ygarr** [comment] 2017-01-13 21:12
8. After restart the app frezes as usual. Than "Raise" window action made work app normally again:
![2017-01-13-231245_347x546_scrot](https://cloud.githubusercontent.com/assets/14309871/21945759/cf265260-d9e5-11e6-943a-317b71fdae94.png)

**Comment by vadrian89** [comment] 2017-01-13 21:21
It is not related to the config file.   
The issue is with the web engine which doesn't renders the page correctly. Qt uses Chromium's blink engine, I remember having similar issues with Chromium in the past(a reason why I returned to Chrome), at least that's what I think.    
If I remember correctly, Chromium used to not render correctly sometimes until I didn't minimised/restored it, that's why I think it is that. I will try and find a solution for it.    
I will let you know as soon as I'm able.

**Comment by vadrian89** [comment] 2017-01-25 19:03
After the last last update(v2.0.6) can you let me know how it behaves if you check the option "Close to Tray" and toggle the visibility? 
"X" from app to close to tray -> tray icon -> show.

**Comment by Ygarr** [comment] 2017-01-31 16:08
After updating just through maintenance tool:
 2017-01-31 18:06:29 ⌚  sidbox in ~/Cumulus
○ → ./Cumulus 
./Cumulus: /home/kdiv/Cumulus/lib/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5)

**Comment by Ygarr** [comment] 2017-01-31 16:24
After reinstall seems all work fine yet. Close to Tray and no freeze

**Comment by vadrian89** [comment] 2017-02-06 17:47
Going to close it since it works.

**Closed by vadrian89** 2017-02-06 17:47 UTC
